# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Skillcraft.Codes'
description: 'arri codes'
permalink: pretty
logo: "https://s.gravatar.com/avatar/4267474913a47aca4b5ef31cf160f72a?s=50"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: home
  url: /
- title: about
  url: /about/
#- title: blog
#  url: /blog/
- title: contact
  url: /contact/
- title: "| papers:"
  url: /papers/
- title: sc2
  url: /papers/skillcraft_regression/


# Footer nav
navigation_footer:
- title: top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
